name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-late00
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm run serve
          wait-on: http://localhost:3000/
